#!/usr/bin/env sh

example() {
  ## Printing the initial arguments

  echo "$@"
  echo "$#"

  # second third
  # 2

  ## Setting arguments

  set -- "first" "$1" "$2" "fourth" "fifth"

  echo
  echo "$@"
  echo "$#"

  # first second third fourth fifth
  # 5

  ## Shifting the arguments list left twice
  # (Replacing the argument $1, $2, $3 values with the values of $3, $4, $5, unsetting $4, $5.)

  shift
  shift

  echo
  echo "$@"
  echo "$#"

  # third fourth fifth
  # 3

  ## Iterating over arguments, removing and substituting arguments

  args_count="$#"
  while [ "$args_count" -gt "0" ]; do
    case "$1" in
      "third")
        shift
        set -- "$@" "THIRD"
      ;;
      "fourth")
        shift
      ;;
      "fifth")
        shift
        set -- "$@" "5th"
      ;;
      "*")
        exit "1"
      ;;
    esac
    args_count="$((args_count - 1))"
  done

  echo
  echo "$@"
  echo "$#"

  # THIRD 5th
  # 2

  ## Arguments from command output

  # shellcheck disable=SC2046
  set -- $(uname -a)

  echo
  echo "$@"
  echo "$#"

  # Linux archpc0 6.10.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Sun, 11 Aug 2024 16:19:06 +0000 x86_64 GNU/Linux
  # 14

  ## Unsetting arguments

  set --

  echo
  echo "$@"
  echo "$#"

  #
  # 0
}

example "second" "third"
