#!/usr/bin/env sh

# Floating point number functions.

# Default scale used by float functions.
float_scale="4"

# Evaluate a floating point number expression.
float_eval() {
  stat="0"
  result="0.0"

  [ "$1" ] && {
    result="$(echo "scale=${float_scale}; ${*}" | bc -q 2> "/dev/null")"

    stat="$?"

    [ "$stat" = "0" ] && [ -z "$result" ] && stat="1"
  }

  echo "$result"
  return "$stat"
}

# Evaluate a floating point number conditional expression.
float_cond() {
  cond="0"

  [ "$1" ] && {
    cond="$(echo "$*" | bc -q 2> "/dev/null")"
    [ "$cond" ] || cond="0"
    [ "$cond" != "0" ] && [ "$cond" != "1" ] && cond="0"
  }

  return "$((cond == "0"))"
}

# Examples

e='12.5 / 3.2'
echo "${e} is $(float_eval "$e")"
e='100.4 / 4.2 + 3.2 * 6.5'
echo "${e} is $(float_eval "$e")"

if float_cond '10.0 > 9.3'; then
  echo "10.0 is greater than 9.3"
fi

if float_cond '10.0 < 9.3'; then
  echo "Oops"
else
  echo "10.0 is not less than 9.3"
fi

a="12.0" b="3.0"
c=$(float_eval "${a} / ${b}")
echo "${a} / ${b} is ${c}"
c=$(float_eval "${a} * ${b}")
echo "${a} * ${b} is ${c}"
a="0.5" b="3.0"
c=$(float_eval "${a} / ${b}")
echo "${a} / ${b} is ${c}"
