#!/usr/bin/env sh
set -eu
export LC_ALL=C

dir="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

echo "# Percentage step increments of the decimal number 255"

third="3.3333333"

for p in 5 "$third" 3 1; do
  echo
  echo "## ${p}%"
  echo

  if [ "$p" = "$third" ]; then
    echo "TODO."
    continue
  fi

  {
    echo "% Decimal Hexadecimal Octal Binary"
    echo "--: ------: ----------: ----: -------:
"
    for x in $(y=0; while [ $y -le "100" ]; do printf "%s " "${y}"; y="$((y+p))"; done); do
       printf "%03d " "$x"
       for b in 10 16 8 2; do
         case "$b" in
          10)
            printf "%03d " "$(echo "scale = 0; obase = ${b}; (255 * (${x} * 0.01)) / 1" | bc)"
          ;;
          16)
            num="$(printf "%s " "$(echo "scale = 0; obase = ${b}; (255 * (${x} * 0.01)) / 1" | bc)")"
            case "${#num}" in
              2)
                printf "%s " "0${num}"
              ;;
              *)
                printf "%s " "$num"
              ;;
            esac
          ;;
          8)
            printf "%03d " "$(echo "scale = 0; obase = ${b}; (255 * (${x} * 0.01)) / 1" | bc)"
          ;;
          2)
            printf "%08d " "$(echo "scale = 0; obase = ${b}; (255 * (${x} * 0.01)) / 1" | bc)"
          ;;
         esac
       done
       echo
    done 
  } | column -t -R - -o " | " | sed -e 's/^/| /g' -e 's/$/ |/g'
done
