#!/usr/bin/env sh

tick="1"
target="20"
reset_sig="USR1"

(
  elapsed="0"

  trap 'echo "Timer reset (${reset_sig})"
  elapsed="$((-tick))"' "$reset_sig"

  echo "${elapsed} / ${target}"

  while true; do
    while [ "$elapsed" -lt "$target" ]; do
      sleep "$tick" &
      wait "$!"
      elapsed="$((elapsed + tick))"

      echo "${elapsed} / ${target}"
    done

    # ... commands to run after the timer expires ...

    # Conditionally resetting the timer after it has expired:
    # if [ "$some_reset_condition" = "1" ]; then
    #   elapsed="0"
    #   continue
    # fi

    exit
  done
) &

sleeper_pid="$!"

echo "Timer started.
"
echo "Timer PID: ${!}
Reset signal: ${reset_sig}

Tick: ${tick}
Target: ${target}

Reset command:
kill -${reset_sig} ${!}

Caller PID: ${$}
"

trap 'kill -9 "$sleeper_pid"' INT TERM QUIT

trap 'echo "
Exiting timer..."' EXIT

wait "$!"
